# creates namespace named "mdm-gateway-dev"
apiVersion: v1
kind: Namespace
metadata:
  name: mdm-gateway-dev
  annotations:
    configmanagement.gke.io/cluster-selector: tif-dev-clusters
  labels:
    istio-injection: enabled
    environment-type: dev
