# creates namespace named "mdm-enterprisesearch-mra-dev"
apiVersion: v1
kind: Namespace
metadata:
  name: mdm-enterprisesearch-mra-dev
  annotations:
    configmanagement.gke.io/cluster-selector: tif-dev-clusters
  labels:
    istio-injection: enabled
    environment-type: dev
